### ISSUE TITLE
In same WE project, how i can refer my elasticsearch service?

### ISSUE THREAD

**Issue by diegonvs** [wedeploy/demo-elasticsearch#7]
I've tried set up `http://{es(my service id), elasticsearch, localhost, }:9200|9300` but none of these options kibana have listened to.

**Comment by albertininm** [comment]
Fixed this issue using two official images with the same version: `docker.elastic.co/kibana/kibana:6.2.4`, `docker.elastic.co/elasticsearch/elasticsearch:6.2.4`
and referring ES via environment variables `ELASTICSEARCH_URL`.
